= ReactiveX Observables
Pradeep
2018-06-06
:jbake-type: post
:jbake-status: draft
:jbake-tags: reactiveX, observables
:jake-category: reactiveX
:jbake-summary: ..
:jbake-image: 

Observable emit values over the time and observer, who is interested to receive these values should subscribe for it. On the availability of values observable will push them to subscribers/observers. Observer will not wait for the values so they are non-blocking and they only act when a value is pushed towards them.

Other than the values, observable will pass error or complete notification to the observer and once these notification is received then the subscription closes and no more values will be passed.

Marble diagrams are the best way to show the flow of values between observable and observer. Below image show a observable which emits even numbers.

<image>

*link:http://rxmarbles.com[rxmarbles]* is the best site to play with observables. This site provides an interactive graphics to show how values change from observables to observer.

Imagine observable is like a water tap, where the water flows continuously.

==== Observable chains

Values traversing between observable and observer can be changed by introducing an intermediate observable. This is the more powerful way to change the values before they reach observer, instead of observer changing by itself. Adding and removing intermediate observables makes the flow flexible.

In this chain an observable acts like an observer to its parent Observable and finally this chain terminates at the subscriber.

<image>

==== Hot and Cold Observables

An hot observable emits values as soon as it is created. Observers who joined later will receive values from middle.

<image>

Cold observable waits for observer to subscribe before emitting values. Observer will see all emitted values.

<image>

==== Observable operators

ReactiveX provides wide variety of operators. We can apply these operators on the emitted values from observables to transform, filter, aggregate, merge and many more. 