= SDKMAN - for developers
Pradeep
2018-06-06
:jbake-type: post
:jbake-status: draft
:jbake-tags: sdkman, tools
:jake-category: tools
:jbake-summary: ..
:jbake-image: 

As a developers we may some times want multiple java versions on our computers. Lets say we want to have java 8 to run a reservation application and java 10 to learn new stuff. We can install both of them but we need to keep switch PATHS based on the requirement. These lower level changes can become more complex if we want to add more java versions. It doesn't just stop at java, reservation application depends on some old maven but we also need latest version of maven for other projects, then we need to manage multiple maven versions.

==== SDKMAN

*link:https://sdkman.io/[SDKMAN]* is a Software Development Kit Manager for java developers. It provides a CLI interface to manage multiple versions of Java SDK's. Using this tool we can easily switch, add, remove or update candidates. Candidates are nothing but the java SDK's managed by SDKMAN.

Installation of SDKMAN is easy on linux based operation systems because it is written in bash but for Windows we need to have Cygwin or MSYS+MinGW. Go through this *link:https://sdkman.io/install[link]* for installation steps.

Note that SDKMAN will not manage pre-existing candidates. So either you need to uninstall them and reinstall with SDKMAN or you can continue to keep them.

After the installation you can see a hidden folder '.sdkman' in users home directory. This contains a sub-folder named 'candidates' which is used to store all installed candidates. We no need to learn about this directories but this folders will give us an idea of how SDKMAN works internally. 

Candidates folder can contain more than one java sub-folder if we installed multiple java versions and we can add these folders as installed JDK's in Java IDE's (like Eclipse or IntelliJ Idea) so we no need to install java externally for just IDE purpose. 

==== CLI

Lets open a terminal and fire up some commands to see how SDKMAN works. I provides some basic commands which we regularly use but we can also go through this *link:https://sdkman.io/usage:[link]* to learn all available options.

===== List all available
List out all available java versions we can install with SDKMAN
[source,bash]
----
$ sdk list java

================================================================================
Available Java Versions
================================================================================
     9.0.7-zulu                                                                    
     9.0.4-openjdk                                                                 
   * 8.0.172-zulu                                                                  
     8.0.171-oracle                                                                
     7.0.181-zulu                                                                  
     10.0.1-zulu                                                                   
     10.0.1-oracle                                                                 
 > * 10.0.0-openjdk                                                                
                                                                             
================================================================================
+ - local version
* - installed
> - currently in use
================================================================================
----

Above output is from my local machine. Along with the list, it indicates that I have two java versions available on my machine (8.0.172-zulu and 10.0.0-openjdk) out of them java 10 is currently in use.

===== Install candidates

No need to mention version if we want to install latest stable release. In the below example, it installs latest stable java version.
[source,bash]
----
sdk install java
----

While installing it asks if we want this version to be set as default. If we say Yes then it will update the PATH so this effects in all new terminal windows.

Install specific java version
[source,bash]
----
sdk install java 9.0.7-zulu
----

Installs java 9.0.7-zulu 

===== Switching versions

To temporarily switch to different version in current shell window
[source,bash]
----
sdk use java 8.0.172-zulu
----

==== Change default version

To set default version
[source, bash]
----
sdk default java 8.0.172-zulu
----

==== List current versions

To see all current versions
[source,bash]
----
sdk current
----

==== Conclusion

SDKMAN is 


