= Spring Cloud Configuration - Part 2
Pradeep
2018-06-23
:jbake-type: post
:jbake-status: draft
:jbake-tags: spring, cloud, config
:jake-category: spring
:jbake-summary: ..
:jbake-image: 

When other applications starts they will contact config server to get 

<image>


Lets create a basic spring application with out cloud configuration and then we introduce config
Spring application by default loads configuration from application properties, which can be found at src/main/resources folder. 

Lets create and configure a spring web application. Go to *link:https://start.spring.io/[start.spring.io]* and generate a pet-store project with *web* as dependency. See below screenshot for the reference.

<image>

Unzip and open spring project in an IDE. You should see an empty application.properties at src/main/resources and single application initializer class PetStoreApplication.java at src/main/java/com/example/petstore.

Owner of the pet-store wants to publish an alert message on some rest-end point so there customers can access this message. Lets add an alert-message property in the configuration file like below;
.application.properties
----
alert-message=Due to inclement weather conditions pet store is closed tomorrow.
----

To publish this message on a rest-end point lets create a controller and inject this property into it.

[source,java]
----
package com.example.petstore;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class AlertMessageController {

    @Value("${alert-message}")
    String alertMessage; // <1>

    @RequestMapping("/alert-message")
    public String getMessage(){ // <2>
        return alertMessage;
    }
}
----
<1> Spring injects *alert-message* property value from configuration.
<2> REST end point for the customers to get alert-message

Start the spring application, by default spring application starts on 8080 port so hit http://localhost:8080/alert-message in the browser and expect to see message 'Due to inclement weather conditions pet store is closed tomorrow.' as the result.




Lets create a rest controller which listens on */alert* end-point and returns pre-configured message from application properties. So 